### ISSUE TITLE
root is different in Spacy to Displacy.

### ISSUE THREAD

**Issue by i-frost** [explosion/displacy#18]
I find the root in a sentence using Spacy in a jupyter notebook but the root is different in the Displacy graph with the same sentence.

Could this be  a Spacy version difference, how can I tell what version Displacy is using?

If I download Displacy can I use the latest version of Spacy?

**Comment by i-frost** [comment]
Having thought about it I reckon its different models I'm using, can the model be specified as a option?

I am using nltk.pretty_print to see the actual tree of the sentence but obviously I would prefer to use Displacy!

**Comment by nixphix** [comment]
@i-frost 
Yes the displaCy demo uses an older model, the one you are getting in your Jupyter notebook is more accurate. If you setup a local displaCy it should render the same result as your notebook. 

I'm really not sure of switching between different version of models.

**Comment by i-frost** [comment]
OK I will setup locally.
