### ISSUE TITLE
displacy.svg download fails

### ISSUE THREAD

**Issue by hyperdo** [explosion/displacy#4]
Both in the [demo](https://demos.explosion.ai/displacy) and in the harp client, the download button prompts a download, but Chrome says "Failed - No file".

**Comment by ines** [comment]
Ah, when I refactored the element rendering, I forgot to add the correct ID to the SVG element. Fixing this now!

The download function uses `XMLSerializer()` and currently just selects the SVG by its ID. Maybe not the most elegant way to do this, so I might give it another update soon.
